# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92516a7fc2a13289e7ccc56ea174ef5aa337ce3852a35a5c767d4fb8d92766a299268b404805968db7a8c5b239fd3f7749828b05caafc03d3d3a2b543b1ce207

test:
  secret_key_base: 92cfb8b1f41b6184c41509af029901477331fe99dd3b1680f255a408b1af9b156b0cfff4c4f9130c21900832a3f6272c5985bb0021ab4b14c6fe081d59c3c1a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
